import stats from "../data/stats.json";

export const OFUDA_FACTS: Record<string, string[]> = {
  en: [
    "I've spent more than half my life in a code editor at this point. I'm starting to see the syntax when I close my eyes.",
    `${stats.commitCount} commits in this portfolio alone. Every single one was a battle with my own perfectionism.`,
    "I've watched Jujutsu Kaisen more than three times. Honestly, I'm still not over it.",
    "Watching Jujutsu Kaisen Culling Game right now. If I respond slowly, you know why.",
    "Most people think I'm just a student, but I was building real systems when they were still learning loops.",
    "Building EyesOn feels like unfinished business. It's the kind of project that keeps me up at night until the logic is perfect.",
    "Next.js over Vite. Always. I build for the world, not just my local machine.",
    "I've solved 300+ problems on LeetCode. Each one was a lesson in how much I still have to learn.",
    "If I get stuck at 2 AM, I don't walk away. I stay right here, explaining the bug to an AI until the solution reveals itself.",
    "I write poetry with the same hands that write go-routines. Different languages, same intent.",
    "I sing when nobody is listening. Mostly Ed Sheeran. Mostly 'Shape of You'.",
    "2,200 commits across all my projects. That's a lot of late nights and cold coffee.",
    "I once reduced WhatsApp's desktop RAM from 370MB to 90MB. That feeling was better than any grade I've ever received.",
    "The Sixth Sense is my favorite movie. I love stories that make you question everything you've just seen.",
    "I grew up in Varanasi. The oldest city in the world. It gives you a different perspective on time.",
    "I've watched Death Note. It's the reason I started questioning the 'obvious' solutions.",
    "My Hero Academia taught me that a 'Quirk' is only a weakness if you don't know how to use it.",
    "I once worked on a Salesforce task for 14 hours straight. I don't recommend it, but I'd do it again.",
    "I have a GPA of 8.87. It looks good on paper, but the projects in my GitHub matter more to me.",
    "I taught myself Rust and Tauri just to see if I could. Turns out, I could.",
    "Varanasi is my home. It's where I learned that you can find peace even in total chaos.",
    "Breaking Bad. Game of Thrones. I've seen the greats. Still looking for a show that hits me that hard again.",
    "I study at Chandigarh University, but my real classroom is a terminal window.",
    "I once cleaned a dataset of 5,000 records by hand. It was tedious, but the results were beautiful.",
    "Family Guy is my 'switch off' show. Even an engineer needs to laugh at something stupid sometimes.",
    "I built an AI that detects diseases with 96% accuracy. That was the moment I realized code can save lives.",
    "I prefer Go for systems. It's clean, it's fast, and it doesn't try to be something it's not.",
    "I use Tailwind CSS because I believe constraints actually make you more creative.",
    "My documentation is 20 pages long because if I can't explain it simply, I don't really understand it.",
    "I built a Windows optimizer that the OS didn't even know it needed. I love making things faster.",
    "I once integrated the Shazam API into a project just to see how the math worked.",
    "Response times under 200ms. If it's slower, I haven't finished the job yet.",
    "Watched Dan Da Dan alone at 2 AM. It's weird, it's brilliant, and I'm not sure who to recommend it to yet.",
    "I handle 10,000+ records in IndexedDB without breaking a sweat. It's all about the architecture.",
    "Most people think I'm quiet, but I'm actually just thinking about a project I haven't started yet.",
    "Ed Sheeran has been my top artist for years. His songwriting is just... efficient.",
    "I used Python for data science, but my heart stays with Go and Rust.",
    "I have a minor in Data Science. I love finding patterns in the noise.",
    "I've seen every episode of Breaking Bad. Walter White is a lesson in what happens when you let your ego lead.",
    "I don't just write code; I ideate. 50% of my day is spent thinking about the 'why' before the 'how'.",
    `I've made ${stats.commitCount} commits to this exact website. And I'm not done yet.`,
    "I once built a sync engine with Merkle Trees. That was a long week.",
    "The Culling Game arc in Jujutsu Kaisen is peak fiction. Change my mind.",
    "I once sang 'Shape of You' for a full hour just to get the vocal runs perfect.",
    "I've watched more than ten anime series since I started in September 2025. I'm catching up fast.",
    "I built a platform for spiritual guidance. It's funny how a coder can help people find peace.",
    "I'm currently working on a project called EyesOn. It's the most ambitious thing I've tried yet.",
    "You're reading this because I spent three hours perfecting the animation of this specific card.",
    "I built this. All of it. From the first line of Go to the last CSS keyframe. Welcome to my mind."
  ],
  ja: [
    "これまで人生の半分以上をコードエディタの中で過ごしてきました。目を閉じると構文が見えてくるようになります。",
    `${stats.commitCount}個のコミットがこのポートフォリオだけで行われました。一つ一つが自分自身の完璧主義との戦いでした。`,
    "呪術廻戦は3回以上見ました。正直、まだ抜け出せていません。",
    "今、呪術廻戦の死滅回游を見ています。返信が遅かったら、理由はわかりますよね。",
    "多くの人は私がただの学生だと思っていますが、彼らがまだループを学んでいた頃に私は本物のシステムを構築していました。",
    "EyesOnを構築することは、やり残した仕事のように感じます。ロジックが完璧になるまで夜も眠れないようなプロジェクトです。",
    "ViteよりNext.js。常に。自分のローカルマシンだけでなく、世界のために構築します。",
    "LeetCodeで300以上の問題を解決しました。一つ一つが、まだ学ぶべきことがどれほどあるかを教えてくれる教訓でした。",
    "午前2時に行き詰まっても、立ち去りません。解決策が見つかるまで、AIにバグを説明しながらここに留まります。",
    "Goルーチンを書くのと同じ手で詩を書きます。言語は違えど、意図は同じです。",
    "誰も聞いていない時に歌います。主にエド・シーラン。主に'Shape of You'。",
    "全プロジェクトを通じて1,900のコミット。多くの深夜作業と冷めたコーヒーの結果です。",
    "かつてWhatsAppのデスクトップRAMを370MBから90MBに削減しました。あの感覚は、これまで受けたどの成績よりも素晴らしかったです。",
    "シックス・センスは私のお気に入りの映画です。見たばかりのものをすべて疑わせるような物語が大好きです。",
    "私はバラナシで育ちました。世界最古の都市です。それは時間に異なる視点を与えてくれます。",
    "デスノートを見ました。それが、私が「当たり前」の解決策を疑い始めた理由です。",
    "僕のヒーローアカデミアは、「個性」は使い道を知らなければただの弱点にすぎないことを教えてくれました。",
    "かつてSalesforceの課題に14時間連続で取り組みました。お勧めはしませんが、またやるでしょう。",
    "GPAは8.87です。紙の上では良く見えますが、GitHubのプロジェクトの方が私にとって重要です。",
    "自分ができるかどうか確かめるためだけにRustとTauriを独学しました。結果、できました。",
    "バラナシは私の故郷です。そこは、完全なカオスの中でも平和を見つけられることを学んだ場所です。",
    "ブレイキング・バッド。ゲーム・オブ・スローンズ。名作は見てきました。またそれほど衝撃を受ける作品を探しています。",
    "チャンディーガル大学で学んでいますが、本当の教室はターミナルウィンドウです。",
    "かつて5,000件のレコードからなるデータセットを手作業でクリーンアップしました。退屈でしたが、結果は美しいものでした。",
    "ファミリー・ガイは私の「スイッチオフ」作品です。エンジニアでも、時にはバカげたことで笑う必要があります。",
    "96%の精度で病気を検出するAIを構築しました。コードが命を救えることに気づいた瞬間でした。",
    "システムにはGoを好みます。クリーンで速く、自分ではないものになろうとしません。",
    "Tailwind CSSを使っているのは、制約が実際に人をよりクリエイティブにすると信じているからです。",
    "私のドキュメントは20ページに及びます。簡単に説明できなければ、本当に理解したとは言えないからです。",
    "OS自身も必要だとは知らなかったWindowsオプティマイザーを構築しました。物事を速くすることが大好きです。",
    "数学の仕組みを確かめるためだけに、Shazam APIをプロジェクトに統合したことがあります。",
    "レスポンスタイムは200ms未満。それより遅ければ、まだ仕事は終わっていません。",
    "午前2時に一人でダンダダンを見ました。奇妙で、素晴らしく、まだ誰に勧めるべきか迷っています。",
    "汗をかくことなくIndexedDBで10,000件以上のレコードを処理します。すべてはアーキテクチャ次第です。",
    "多くの人は私が物静かだと思っていますが、実際にはまだ始めていないプロジェクトのことを考えているだけです。",
    "エド・シーランは何年も私のトップアーティストです。彼のソングライティングは、ただ...効率的です。",
    "データサイエンスにはPythonを使いましたが、心はGoとRustにあります。",
    "データサイエンスを副専攻しています。ノイズの中にパターンを見つけることが大好きです。",
    "ブレイキング・バッドの全エピソードを見ました。ウォルター・ホワイトは、エゴに身を任せるとどうなるかを教えてくれる教訓です。",
    "ただコードを書くだけではありません。構想します。1日の50%は「いかに」の前に「なぜ」を考えることに費やされます。",
    `このウェブサイトのためだけに${stats.commitCount}回のコミットをしました。まだ終わっていません。`,
    "かつてマークルツリーを使った同期エンジンを構築しました。長い一週間でした。",
    "呪術廻戦の死滅回遊編はフィクションの頂点です。異論は認めます。",
    "ボーカルランを完璧にするためだけに、'Shape of You'を1時間丸々歌ったことがあります。",
    "2025年9月に始めてから10シリーズ以上のアニメを見ました。急速に追いついています。",
    "精神的ガイダンスのためのプラットフォームを構築しました。コーダーが人々の心の平安を助けられるのは面白いことです。",
    "現在、EyesOnというプロジェクトに取り組んでいます。これまでで最も野心的な試みです。",
    "これを読んでいるのは、私がこの特定のカードのアニメーションを完璧にするために3時間を費やしたからです。",
    "私がこれを作りました。すべてです。Goの最初の行から最後のCSSキーフレームまで。私の心の中へようこそ。"
  ],
  ko: [
    "지금까지 제 인생의 절반 이상을 코드 에디터에서 보냈습니다. 눈을 감으면 구문이 보이기 시작합니다.",
    `${stats.commitCount}개의 커밋이 이 포트폴리오에서만 이루어졌습니다. 하나하나가 저 자신의 완벽주의와의 싸움이었습니다.`,
    "주술회전을 세 번 이상 봤습니다. 솔직히 아직 헤어 나오지 못했습니다.",
    "지금 주술회전 사멸회유를 보고 있습니다. 답장이 느리다면 이유를 아시겠죠.",
    "대부분의 사람들은 제가 그저 학생이라고 생각하지만, 그들이 루프를 배우고 있을 때 저는 실제 시스템을 구축하고 있었습니다.",
    "EyesOn을 구축하는 것은 마치 끝나지 않은 업무처럼 느껴집니다. 로직이 완벽해질 때까지 밤을 지새우게 만드는 그런 프로젝트입니다.",
    "Vite보다는 Next.js. 언제나입니다. 제 로컬 머신뿐만 아니라 세상을 위해 구축합니다.",
    "LeetCode에서 300개 이상의 문제를 해결했습니다. 각각의 문제는 제가 아직 배워야 할 것이 얼마나 많은지 알려주는 교훈이었습니다.",
    "새벽 2시에 막히더라도 포기하지 않습니다. 해결책이 나타날 때까지 AI에게 버그를 설명하며 이곳에 머뭅니다.",
    "Go 루틴을 작성하는 것과 같은 손으로 시를 씁니다. 언어는 다르지만 의도는 같습니다.",
    "아무도 듣지 않을 때 노래를 부릅니다. 주로 에드 시런, 주로 'Shape of You'를 부릅니다.",
    "모든 프로젝트를 통틀어 1,900개의 커밋. 수많은 밤샘 작업과 식은 커피의 결과입니다.",
    "한번은 WhatsApp의 데스크톱 RAM 사용량을 370MB에서 90MB로 줄였습니다. 그 기분은 어떤 학점을 받았을 때보다 좋았습니다.",
    "식스 센스는 제가 가장 좋아하는 영화입니다. 방금 본 모든 것을 의심하게 만드는 이야기를 좋아합니다.",
    "저는 바라나시에서 자랐습니다. 세계에서 가장 오래된 도시죠. 그곳은 시간에 대한 다른 관점을 갖게 해줍니다.",
    "데스노트를 봤습니다. 그것이 제가 '당연한' 해결책들에 의문을 갖기 시작한 이유입니다.",
    "나의 히어로 아카데미아는 '개성'이 사용법을 모르면 단지 약점일 뿐이라는 것을 가르쳐 주었습니다.",
    "한번은 Salesforce 과제를 14시간 연속으로 작업했습니다. 추천하지는 않지만, 다시 할 의향은 있습니다.",
    "학점은 8.87입니다. 서류상으론 좋아 보이지만, GitHub의 프로젝트들이 제게는 더 중요합니다.",
    "할 수 있는지 확인해보고 싶어서 Rust와 Tauri를 독학했습니다. 결과적으로 할 수 있었습니다.",
    "바라나시는 제 고향입니다. 완전한 혼돈 속에서도 평화를 찾을 수 있다는 것을 배운 곳이죠.",
    "브레이킹 배드, 왕좌의 게임. 명작들은 다 봤습니다. 다시 그 정도로 충격을 줄 작품을 찾고 있습니다.",
    "찬디가르 대학교에서 공부하고 있지만, 저의 진짜 교실은 터미널 창입니다.",
    "한번은 5,000개의 레코드가 담긴 데이터셋을 수작업으로 정리했습니다. 지루했지만 결과는 아름다웠습니다.",
    "패밀리 가이는 제 '휴식' 프로그램입니다. 엔지니어도 가끔은 바보 같은 것을 보며 웃어야 합니다.",
    "질병을 96% 정확도로 감지하는 AI를 구축했습니다. 코드가 생명을 구할 수 있다는 것을 깨달은 순간이었습니다.",
    "시스템 프로그래밍에는 Go를 선호합니다. 깔끔하고 빠르며, 본연의 기능에 충실하기 때문입니다.",
    "Tailwind CSS를 사용하는 이유는 제약이 실제로 사람을 더 창의적으로 만든다고 믿기 때문입니다.",
    "제 문서가 20페이지에 달하는 이유는, 간단하게 설명할 수 없다면 제가 그것을 제대로 이해하지 못한 것이기 때문입니다.",
    "OS조차 필요로 하는지 몰랐던 Windows 최적화 도구를 구축했습니다. 무언가를 빠르게 만드는 것을 좋아합니다.",
    "수학이 어떻게 작동하는지 보려고 Shazam API를 프로젝트에 통합해 본 적이 있습니다.",
    "응답 시간 200ms 미만. 그보다 느리다면 아직 일을 끝내지 않은 것입니다.",
    "새벽 2시에 혼자 다ンダ단(Dan Da Dan)을 봤습니다. 기괴하고 천재적이며, 아직 누구에게 추천해야 할지 모르겠습니다.",
    "IndexedDB에서 10,000개 이상의 레코드를 문제없이 처리합니다. 모든 것은 아키텍처에 달려 있습니다.",
    "대부분의 사람들이 제가 조용하다고 생각하지만, 사실 저는 아직 시작하지 않은 프로젝트를 생각하고 있을 뿐입니다.",
    "에드 시런은 수년 동안 제가 가장 좋아하는 아티스트입니다. 그의 작곡은 정말... 효율적입니다.",
    "데이터 과학을 위해 Python을 사용했지만, 제 마음은 Go와 Rust에 있습니다.",
    "데이터 과학을 부전공하고 있습니다. 소음 속에서 패턴을 찾는 것을 좋아합니다.",
    "브레이킹 배드의 모든 에피소드를 봤습니다. 월터 화이트는 자존심이 앞설 때 어떤 일이 벌어지는지 보여주는 교훈입니다.",
    "저는 단순히 코드만 쓰지 않습니다. 구상합니다. 하루의 50%는 '어떻게' 이전에 '왜'를 생각하는 데 씁니다.",
    `바로 이 웹사이트를 위해 ${stats.commitCount}번의 커밋을 했습니다. 그리고 아직 끝내지 않았습니다.`,
    "한번은 머클 트리를 이용한 동기화 엔진을 구축했습니다. 긴 한 주였습니다.",
    "주술회전의 사멸회유 편은 픽션의 정점입니다. 제 생각을 바꿔보시죠.",
    "보컬 런을 완벽하게 하려고 'Shape of You'를 한 시간 내내 부른 적이 있습니다.",
    "2025년 9월에 시작한 이후로 10개 이상의 애니메이션 시리즈를 봤습니다. 빠르게 따라잡고 있습니다.",
    "영적 가이드를 위한 플랫폼을 구축했습니다. 프로그래머가 사람들의 평화를 도울 수 있다는 점이 흥미롭습니다.",
    "현재 EyesOn이라는 프로젝트를 진행 중입니다. 지금까지 시도한 것 중 가장 야심 찬 프로젝트입니다.",
    "당신이 이것을 읽고 있는 이유는 제가 이 특정 카드의 애니메이션을 완벽하게 만드는 데 3시간을 썼기 때문입니다.",
    "제가 이것을 만들었습니다. 모든 것을요. Go의 첫 번째 줄부터 마지막 CSS 키프레임까지. 제 마음속에 오신 것을 환영합니다."
  ],
  "zh-tw": [
    "到目前為止，我生命中超過一半的時間都在程式碼編輯器中度過。當我閉上眼睛時，我開始能看到語法。",
    `光是在這個作品集中，就有 ${stats.commitCount} 次提交。每一次都是與我自己完美主義的戰鬥。`,
    "《咒術迴戰》我看了不三遍。說實話，我還沒緩過來。",
    "現在正在看《咒術迴戰》死滅迴游篇。如果我回覆慢了，你知道原因的。",
    "大多數人認為我只是個學生，但當他們還在學習迴圈時，我就已經在構建真實的系統了。",
    "構建 EyesOn 感覺就像是未完成的工作。它是那種會讓我熬夜，直到邏輯完美為止的專案。",
    "永遠選擇 Next.js 而非 Vite。我為世界而建，而不僅僅是為了我的個人電腦。",
    "我已經解決了 LeetCode 上 300 多道題目。每一道都在教導我還有多少東西需要學習。",
    "如果我在凌晨 2 點卡住了，我不會離開。我會待在這裡，向 AI 解釋這個錯誤，直到解決方案自動浮現。",
    "我用寫 Go 協程的雙手寫詩。不同的語言，同樣的意圖。",
    "沒人聽的時候我會唱歌。主要是艾德·希蘭。主要是《Shape of You》。",
    "我所有專案累計有 1,900 次提交。那是無數個深夜和冷咖啡的成果。",
    "我曾將 WhatsApp 的桌面記憶體占用從 370MB 降至 90MB。那種感覺比我得過的任何成績都要好。",
    "《靈異第六感》是我最喜歡的電影。我喜歡那些讓你對剛看過的一切產生懷疑的故事。",
    "我在瓦拉納西長大。世界上最古老的城市。它賦予你不同的時間觀。",
    "我看過《死亡筆記本》。這就是我開始質疑「顯而易見」的解決方案的原因。",
    "《我的英雄學院》教會我，如果你不知道如何使用，「個性」就只是一個弱點。",
    "我曾連續工作 14 個小時處理一個 Salesforce 任務。我不推薦這樣做，但我會再次嘗試。",
    "我的平均績點 (GPA) 是 8.87。雖然紙面上看起來不錯，但我 GitHub 上的專案對我來說更有意義。",
    "我自學了 Rust 和 Tauri，只是為了看看我能不能做到。事實證明，我可以。",
    "瓦拉納西是我的家。在那裡我學會了即使在完全的混亂中也能找到平靜。",
    "《絕命毒師》、《權力的遊戲》，我看過這些經典。我仍在尋找能再次給我如此震撼的作品。",
    "我在昌迪加爾大學就讀，但我真正的教室是終端機視窗。",
    "我曾手動清理過一個擁有 5,000 條記錄的資料集。雖然乏味，但結果很漂亮。",
    "《蓋酷家庭》是我「放鬆」時看的節目。即使是工程師，有時也需要對一些愚蠢的事情大笑。",
    "我開發了一個準確率達 96% 的疾病偵測 AI。那是我意識到程式碼可以拯救生命的時刻。",
    "系統開發我偏好 Go。它乾淨、快速，而且不試圖偽裝成它原本不具備的樣子。",
    "我使用 Tailwind CSS 是因為我相信限制實際上會讓你更有創意。",
    "我的文件長達 20 頁，因為如果我不能簡單地解釋它，我就不是真的理解它。",
    "我開發了一個連作業系統都不知道自己需要的 Windows 優化器。我熱愛讓事情變得更快。",
    "我曾將 Shazam API 整合到一個專案中，只是為了看看數學是如何運作的。",
    "響應時間低於 200 毫秒。如果慢於這個數字，我的工作就還沒完成。",
    "凌晨 2 點獨自看了《膽大黨》。它很古怪，很出色，我還不確定該向誰推薦它。",
    "我在 IndexedDB 中處理 10,000 多條記錄而毫不費力。這一切都取決於架構。",
    "大多數人認為我很安靜，但實際上我只是在思考一個還沒啟動的專案。",
    "多年前艾德·希蘭就是我最喜歡的藝人。他的創作簡直... 高效。",
    "我曾將 Python 用於資料科學，但我的心始終屬於 Go 和 Rust。",
    "我輔修資料科學。我熱愛從雜訊中尋找模式。",
    "我看過《絕命毒師》的每一集。華特·懷特是一個教訓，告訴你當你讓自我主導時會發生什麼。",
    "我不只是寫程式碼；我思考概念。我一天中 50% 的時間花在思考「為什麼」而不是「如何做」。",
    `我為這個網站進行了 ${stats.commitCount} 次提交。而且我還沒完成。`,
    "我曾利用默克爾樹構建過一個同步引擎。那是漫長的一週。",
    "《咒術迴戰》的死滅迴游篇是虛構作品的巔峰。不服來辯。",
    "我曾為了讓轉音完美，連續唱了一整小時的《Shape of You》。",
    "自 2025 年 9 月開始以來，我已經看了十部以上的動畫系列。我正在快速趕上進度。",
    "我構建了一個精神導航平台。有趣的是，一名程式設計師竟然能幫助人們找到平靜。",
    "目前我正在開發一個名為 EyesOn 的專案。這是我目前嘗試過最具野心的專案。",
    "你之所以在讀這段文字，是因為我花了三個小時來完善這張特定卡片的動畫。",
    "我構建了這一切。全部。從第一行 Go 到最後一個 CSS 關鍵幀。歡迎來到我的內心世界。"
  ],
  hi: [
    "इस समय तक मैंने अपना आधा से ज्यादा जीवन एक कोड एडिटर में बिताया है। जब मैं अपनी आँखें बंद करता हूँ तो मुझे सिंटैक्स दिखने लगता है।",
    `अकेले इस पोर्टफोलियो में ${stats.commitCount} कमिट हैं। हर एक मेरे अपने पूर्णतावाद (perfectionism) के साथ एक लड़ाई थी।`,
    "मैंने जुजुत्सु कैसेन (Jujutsu Kaisen) को तीन बार से अधिक देखा है। सच कहूँ तो, मैं अभी भी इससे उबर नहीं पाया हूँ।",
    "अभी जुजुत्सु कैसेन कलिंग गेम देख रहा हूँ। अगर मैं धीरे जवाब दूँ, तो आप जानते हैं क्यों।",
    "ज़्यादातर लोग सोचते हैं कि मैं सिर्फ एक छात्र हूँ, लेकिन जब वे अभी लूप सीख रहे थे, तब मैं वास्तविक सिस्टम बना रहा था।",
    "EyesOn बनाना अधूरे काम जैसा लगता है। यह उस तरह का प्रोजेक्ट है जो मुझे तब तक रात में जगाए रखता है जब तक कि लॉजिक परफेक्ट न हो जाए।",
    "Vite के ऊपर Next.js। हमेशा। मैं दुनिया के लिए बनाता हूँ, न कि केवल अपनी स्थानीय मशीन के लिए।",
    "मैंने LeetCode पर 300+ समस्याओं को हल किया है। हर एक इस बात का सबक था कि मुझे अभी भी कितना कुछ सीखना है।",
    "अगर मैं रात 2 बजे फंस जाता हूँ, तो मैं दूर नहीं जाता। मैं यहीं रुकता हूँ, एआई को बग समझाता हूँ जब तक कि समाधान खुद सामने न आ जाए।",
    "मैं उन्हीं हाथों से कविता लिखता हूँ जिनसे गो-रूटीन लिखता हूँ। अलग भाषाएँ, एक ही इरादा।",
    "जब कोई नहीं सुन रहा होता है तो मैं गाता हूँ। ज़्यादातर एड शीरन। ज़्यादातर 'Shape of You'।",
    "मेरे सभी प्रोजेक्ट्स में 1,900 कमिट। यह बहुत सारी देर रात और ठंडी कॉफी का नतीजा है।",
    "मैंने एक बार व्हाट्सएप के डेस्कटॉप रैम को 370MB से घटाकर 90MB कर दिया था। वह एहसास मुझे मिली किसी भी ग्रेड से बेहतर था।",
    "द सिक्स्थ सेंस (The Sixth Sense) मेरी पसंदीदा फिल्म है। मुझे ऐसी कहानियाँ पसंद हैं जो आपको अभी देखी गई हर चीज़ पर सवाल उठाने के लिए मजबूर कर दें।",
    "मैं वाराणसी में पला-बढ़ा हूँ। दुनिया का सबसे पुराना शहर। यह आपको समय पर एक अलग दृष्टिकोण देता है।",
    "मैंने डेथ नोट (Death Note) देखा है। यही कारण है कि मैंने 'स्पष्ट' समाधानों पर सवाल उठाना शुरू कर दिया।",
    "माई हीरो एकेडेमिया ने मुझे सिखाया कि एक 'क्विर्क' (Quirk) केवल तभी एक कमजोरी है जब आप नहीं जानते कि इसका उपयोग कैसे करना है।",
    "मैंने एक बार लगातार 14 घंटे सेल्सफोर्स टास्क पर काम किया था। मैं इसकी सिफारिश नहीं करता, लेकिन मैं इसे फिर से करूँगा।",
    "मेरा GPA 8.87 है। यह कागज़ पर अच्छा लगता है, लेकिन मेरे GitHub के प्रोजेक्ट मेरे लिए ज़्यादा मायने रखते हैं।",
    "मैंने खुद को रस्ट (Rust) और टौरी (Tauri) सिखाया सिर्फ यह देखने के लिए कि क्या मैं कर सकता हूँ। पता चला, मैं कर सकता था।",
    "वाराणसी मेरा घर है। यहीं मैंने सीखा कि आप पूर्ण अराजकता में भी शांति पा सकते हैं।",
    "ब्रेकिंग बैड। गेम ऑफ थ्रोन्स। मैंने महान शो देखे हैं। अभी भी एक ऐसे शो की तलाश है जो मुझे फिर से उतनी गहराई से प्रभावित करे।",
    "मैं चंडीगढ़ यूनिवर्सिटी में पढ़ता हूँ, लेकिन मेरी असली क्लासरूम एक टर्मिनल विंडो है।",
    "मैंने एक बार हाथ से 5,000 रिकॉर्ड्स के डेटासेट को साफ़ किया था। यह थकाऊ था, लेकिन परिणाम सुंदर थे।",
    "फैमिली गाय (Family Guy) मेरा 'स्विच ऑफ' शो है। एक इंजीनियर को भी कभी-कभी किसी बेवकूफी भरी चीज़ पर हँसने की ज़रूरत होती है।",
    "मैंने एक एआई बनाया है जो 96% सटीकता के साथ बीमारियों का पता लगाता है। वह क्षण था जब मुझे एहसास हुआ कि कोड जीवन बचा सकता है।",
    "मैं सिस्टम के लिए गो (Go) पसंद करता हूँ। यह साफ है, यह तेज़ है, और यह वह बनने की कोशिश नहीं करता जो यह नहीं है।",
    "मैं टेलविंड सीएसएस (Tailwind CSS) का उपयोग करता हूँ क्योंकि मेरा मानना है कि बाधाएं वास्तव में आपको अधिक रचनात्मक बनाती हैं।",
    "मेरा दस्तावेज़ीकरण 20 पेज लंबा है क्योंकि अगर मैं इसे सरलता से नहीं समझा सकता, तो मैं वास्तव में इसे समझ नहीं पाता।",
    "मैंने एक विंडोज़ ऑप्टिमाइज़र बनाया है जिसकी ओएस को ज़रूरत थी, यह उसे पता भी नहीं था। मुझे चीज़ों को तेज़ बनाना पसंद है।",
    "मैंने एक बार बस यह देखने के लिए कि गणित कैसे काम करता है, एक प्रोजेक्ट में शाज़म एपीआई (Shazam API) को एकीकृत किया था।",
    "प्रतिक्रिया समय (Response times) 200ms से कम। अगर यह धीमा है, तो मैंने अभी तक काम पूरा नहीं किया है।",
    "रात 2 बजे अकेले डैन डा डैन (Dan Da Dan) देखा। यह अजीब है, यह शानदार है, और मुझे अभी तक यकीन नहीं है कि इसकी सिफारिश किसे करनी है।",
    "मैं बिना पसीना बहाए IndexedDB में 10,000+ रिकॉर्ड्स को हैंडल करता हूँ। यह सब आर्किटेक्चर के बारे में है।",
    "ज़्यादातर लोग सोचते हैं कि मैं शांत हूँ, लेकिन असल में मैं बस एक ऐसे प्रोजेक्ट के बारे में सोच रहा हूँ जो मैंने अभी तक शुरू नहीं किया है।",
    "एड शीरन वर्षों से मेरे शीर्ष कलाकार रहे हैं। उनका गीत लेखन बस... कुशल है।",
    "मैंने डेटा साइंस के लिए पायथन का उपयोग किया, लेकिन मेरा दिल गो और रस्ट के साथ रहता है।",
    "डेटा साइंस में मेरा एक माइनर (minor) है। मुझे शोर में पैटर्न खोजना पसंद है।",
    "मैंने ब्रेकिंग बैड का हर एपिसोड देखा है। वाल्टर व्हाइट इस बात का सबक है कि क्या होता है जब आप अपने अहंकार को नेतृत्व करने देते हैं।",
    "मैं सिर्फ कोड नहीं लिखता; मैं विचार करता (ideate) हूँ। मेरे दिन का 50% हिस्सा 'कैसे' से पहले 'क्यों' के बारे में सोचने में बीतता है।",
    `मैंने विशेष रूप से इस वेबसाइट के लिए ${stats.commitCount} कमिट किए हैं। और मैं अभी तक नहीं रुका हूँ।`,
    "मैंने एक बार मर्कल ट्री (Merkle Trees) के साथ एक सिंक इंजन बनाया था। वह एक लंबा सप्ताह था।",
    "जुजुत्सु कैसेन में कलिंग गेम आर्क फिक्शन का शिखर है। मेरी राय बदलें।",
    "मैंने एक बार वोकल रन को परफेक्ट करने के लिए पूरे एक घंटे तक 'Shape of You' गाया था।",
    "सितंबर 2025 में शुरू करने के बाद से मैंने दस से अधिक एनीमे सीरीज़ देखी हैं। मैं बहुत तेज़ी से आगे बढ़ रहा हूँ।",
    "मैंने आध्यात्मिक मार्गदर्शन के लिए एक मंच बनाया है। यह मज़ेदार है कि कैसे एक कोडर लोगों को शांति खोजने में मदद कर सकता है।",
    "मैं वर्तमान में EyesOn नामक प्रोजेक्ट पर काम कर रहा हूँ। यह अब तक की सबसे महत्वाकांक्षी चीज़ है जिसे मैंने आज़माया है।",
    "आप इसे पढ़ रहे हैं क्योंकि मैंने इस विशेष कार्ड के एनीमेशन को परफेक्ट बनाने में तीन घंटे बिताए हैं।",
    "मैंने इसे बनाया है। इसका हर हिस्सा। गो की पहली लाइन से लेकर आखिरी सीएसएस कीफ्रेम तक। मेरे दिमाग में आपका स्वागत है।"
  ],
  fr: [
    "J'ai passé plus de la moitié de ma vie dans un éditeur de code à ce stade. Je commence à voir la syntaxe quand je ferme les yeux.",
    `${stats.commitCount} commits dans ce portfolio seul. Chaque commit a été une bataille contre mon propre perfectionnisme.`,
    "J'ai regardé Jujutsu Kaisen plus de trois fois. Honnêtement, je ne m'en suis toujours pas remis.",
    "Je regarde Jujutsu Kaisen Culling Game en ce moment. Si je réponds lentement, vous savez pourquoi.",
    "La plupart des gens pensent que je ne suis qu'un étudiant, mais je construisais des systèmes réels quand ils apprenaient encore les boucles.",
    "Construire EyesOn ressemble à une affaire inachevée. C'est le genre de projet qui m'empêche de dormir la nuit jusqu'à ce que la logique soit parfaite.",
    "Next.js plutôt que Vite. Toujours. Je construis pour le monde, pas seulement pour ma machine locale.",
    "J'ai résolu plus de 300 problèmes sur LeetCode. Chacun était une leçon sur tout ce qu'il me reste à apprendre.",
    "Si je suis bloqué à 2 heures du matin, je ne m'en vais pas. Je reste ici, expliquant le bug à une IA jusqu'à ce que la solution se révèle.",
    "J'écris de la poésie avec les mêmes mains qui écrivent des go-routines. Langues différentes, même intention.",
    "Je chante quand personne n'écoute. Principalement Ed Sheeran. Surtout 'Shape of You'.",
    "1 900 commits sur l'ensemble de mes projets. C'est beaucoup de nuits tardives et de café froid.",
    "J'ai une fois réduit la RAM de bureau de WhatsApp de 370 Mo à 90 Mo. Ce sentiment était meilleur que n'importe quelle note que j'ai jamais reçue.",
    "Le Sixième Sens est mon film préféré. J'adore les histoires qui font tout remettre en question ce que l'on vient de voir.",
    "J'ai grandi à Varanasi. La plus vieille ville du monde. Cela donne une perspective différente sur le temps.",
    "J'ai regardé Death Note. C'est la raison pour laquelle j'ai commencé à remettre en question les solutions 'évidentes'.",
    "My Hero Academia m'a appris qu'un 'Alter' n'est une faiblesse que si l'on ne sait pas comment l'utiliser.",
    "J'ai une fois travaillé sur une tâche Salesforce pendant 14 heures d'affilée. Je ne le recommande pas, mais je le referais.",
    "J'ai un GPA de 8,87. Ça a l'air bien sur le papier, mais les projets sur mon GitHub comptent plus pour moi.",
    "J'ai appris Rust et Tauri en autodidacte juste pour voir si je pouvais le faire. Il s'avère que je le pouvais.",
    "Varanasi est ma maison. C'est là que j'ai appris qu'on peut trouver la paix même dans le chaos total.",
    "Breaking Bad. Game of Thrones. J'ai vu les classiques. Je cherche encore une série qui me frappe aussi fort à nouveau.",
    "J'étudie à l'Université de Chandigarh, mais ma vraie salle de classe est une fenêtre de terminal.",
    "J'ai une fois nettoyé un jeu de données de 5 000 enregistrements à la main. C'était fastidieux, mais les résultats étaient magnifiques.",
    "Family Guy est ma série 'détente'. Même un ingénieur a besoin de rire de quelque chose de stupide parfois.",
    "J'ai construit une IA qui détecte les maladies avec une précision de 96 %. C'est à ce moment-là que j'ai réalisé que le code peut sauver des vies.",
    "Je préfère Go pour les systèmes. C'est propre, c'est rapide, et ça n'essaie pas d'être quelque chose que ça n'est pas.",
    "J'utilise Tailwind CSS parce que je crois que les contraintes rendent en fait plus créatif.",
    "Ma documentation fait 20 pages car si je ne peux pas l'expliquer simplement, c'est que je ne la comprends pas vraiment.",
    "J'ai construit un optimiseur Windows dont l'OS ne savait même pas qu'il avait besoin. J'adore rendre les choses plus rapides.",
    "J'ai une fois intégré l'API Shazam dans un projet juste pour voir comment le calcul fonctionnait.",
    "Temps de réponse inférieurs à 200 ms. Si c'est plus lent, c'est que je n'ai pas encore fini le travail.",
    "J'ai regardé Dan Da Dan seul à 2 heures du matin. C'est bizarre, c'est brillant, et je ne sais pas encore à qui le recommander.",
    "Je gère plus de 10 000 enregistrements dans IndexedDB sans transpirer. Tout est question d'architecture.",
    "La plupart des gens pensent que je suis calme, mais en réalité je pense juste à un projet que je n'ai pas encore commencé.",
    "Ed Sheeran est mon artiste préféré depuis des années. Son écriture de chansons est juste... efficace.",
    "J'ai utilisé Python pour la science des données, mais mon cœur reste avec Go et Rust.",
    "J'ai une mineure en science des données. J'adore trouver des motifs dans le bruit.",
    "J'ai vu chaque épisode de Breaking Bad. Walter White est une leçon sur ce qui se passe quand on laisse son ego diriger.",
    "Je n'écris pas seulement du code ; j'idéalise. 50 % de ma journée est consacrée à réfléchir au 'pourquoi' avant le 'comment'.",
    `J'ai fait ${stats.commitCount} commits sur ce site web même. Et je n'ai pas encore fini.`,
    "J'ai une fois construit un moteur de synchronisation avec des arbres de Merkle. C'était une longue semaine.",
    "L'arc Culling Game dans Jujutsu Kaisen est le sommet de la fiction. Faites-moi changer d'avis.",
    "J'ai une fois chanté 'Shape of You' pendant une heure entière juste pour parfaire les envolées vocales.",
    "J'ai regardé plus de dix séries animées depuis mes débuts en septembre 2025. Je rattrape mon retard rapidement.",
    "J'ai construit une plateforme de guidance spirituelle. C'est drôle comme un codeur peut aider les gens à trouver la paix.",
    "Je travaille actuellement sur un projet appelé EyesOn. C'est la chose la plus ambitieuse que j'aie essayée jusqu'à présent.",
    "Vous lisez ceci parce que j'ai passé trois heures à perfectionner l'animation de cette carte spécifique.",
    "J'ai construit ça. Tout ça. De la première ligne de Go au dernier keyframe CSS. Bienvenue dans mon esprit."
  ],
  id: [
    "Saya telah menghabiskan lebih dari separuh hidup saya di editor kode saat ini. Saya mulai melihat sintaksis ketika saya memejamkan mata.",
    `${stats.commitCount} commit di portofolio ini saja. Setiap commit adalah pertempuran dengan perfeksionisme saya sendiri.`,
    "Saya sudah menonton Jujutsu Kaisen lebih dari tiga kali. Sejujurnya, saya masih belum bisa melupakannya.",
    "Sedang menonton Jujutsu Kaisen Culling Game sekarang. Jika saya merespons lambat, Anda tahu alasannya.",
    "Kebanyakan orang mengira saya hanya seorang pelajar, tetapi saya sudah membangun sistem nyata ketika mereka masih mempelajari perulangan.",
    "Membangun EyesOn terasa seperti urusan yang belum selesai. Ini adalah jenis proyek yang membuat saya terjaga di malam hari sampai logikanya sempurna.",
    "Next.js daripada Vite. Selalu. Saya membangun untuk dunia, bukan hanya mesin lokal saya.",
    "Saya telah menyelesaikan 300+ masalah di LeetCode. Masing-masing adalah pelajaran tentang seberapa banyak yang masih harus saya pelajari.",
    "Jika saya terjebak jam 2 pagi, saya tidak akan pergi. Saya tetap di sini, menjelaskan bug kepada AI sampai solusinya terungkap.",
    "Saya menulis puisi dengan tangan yang sama dengan yang menulis go-routines. Bahasa berbeda, niat sama.",
    "Saya bernyanyi saat tidak ada yang mendengarkan. Terutama Ed Sheeran. Terutama 'Shape of You'.",
    "1.900 commit di semua proyek saya. Itu berarti banyak malam larut dan kopi dingin.",
    "Saya pernah mengurangi RAM desktop WhatsApp dari 370MB menjadi 90MB. Perasaan itu lebih baik daripada nilai apa pun yang pernah saya terima.",
    "The Sixth Sense adalah film favorit saya. Saya suka cerita yang membuat Anda mempertanyakan semua yang baru saja Anda lihat.",
    "Saya besar di Varanasi. Kota tertua di dunia. Ini memberi Anda perspektif berbeda tentang waktu.",
    "Saya sudah menonton Death Note. Itulah alasan saya mulai mempertanyakan solusi yang 'jelas'.",
    "My Hero Academia mengajari saya bahwa 'Quirk' hanyalah kelemahan jika Anda tidak tahu cara menggunakannya.",
    "Saya pernah mengerjakan tugas Salesforce selama 14 jam berturut-turut. Saya tidak merekomendasikannya, tetapi saya akan melakukannya lagi.",
    "IPK saya 8,87. Terlihat bagus di atas kertas, tetapi proyek di GitHub saya lebih penting bagi saya.",
    "Saya belajar Rust dan Tauri secara otodidak hanya untuk melihat apakah saya bisa. Ternyata, saya bisa.",
    "Varanasi adalah rumah saya. Di sanalah saya belajar bahwa Anda bisa menemukan kedamaian bahkan dalam kekacauan total.",
    "Breaking Bad. Game of Thrones. Saya sudah menonton yang terbaik. Masih mencari acara yang bisa membuat saya terkesan sekuat itu lagi.",
    "Saya kuliah di Universitas Chandigarh, tetapi ruang kelas saya yang sebenarnya adalah jendela terminal.",
    "Saya pernah membersihkan dataset berisi 5.000 catatan dengan tangan. Membosankan, tapi hasilnya indah.",
    "Family Guy adalah acara 'istirahat' saya. Bahkan seorang insinyur perlu menertawakan sesuatu yang bodoh sesekali.",
    "Saya membangun AI yang mendeteksi penyakit dengan akurasi 96%. Itulah saat saya menyadari kode dapat menyelamatkan nyawa.",
    "Saya lebih suka Go untuk sistem. Bersih, cepat, dan tidak mencoba menjadi sesuatu yang bukan dirinya.",
    "Saya menggunakan Tailwind CSS karena saya percaya batasan justru membuat Anda lebih kreatif.",
    "Dokumentasi saya panjangnya 20 halaman karena jika saya tidak bisa menjelaskannya dengan sederhana, saya tidak benar-benar memahaminya.",
    "Saya membangun pengoptimal Windows yang bahkan OS tidak tahu dibutuhkannya. Saya suka membuat segalanya lebih cepat.",
    "Saya pernah mengintegrasikan API Shazam ke dalam proyek hanya untuk melihat cara kerja matematikanya.",
    "Waktu respons di bawah 200 ms. Jika lebih lambat, saya belum menyelesaikan tugasnya.",
    "Menonton Dan Da Dan sendirian jam 2 pagi. Aneh, brilian, dan saya belum yakin kepada siapa harus merekomendasikannya.",
    "Saya menangani 10.000+ catatan di IndexedDB tanpa berkeringat. Semuanya tergantung pada arsitektur.",
    "Kebanyakan orang mengira saya pendiam, padahal sebenarnya saya hanya sedang memikirkan proyek yang belum saya mulai.",
    "Ed Sheeran telah menjadi artis top saya selama bertahun-tahun. Penulisan lagunya sangat... efisien.",
    "Saya menggunakan Python untuk data science, tetapi hati saya tetap di Go dan Rust.",
    "Saya mengambil minor di Data Science. Saya suka menemukan pola dalam kebisingan.",
    "Saya telah menonton setiap episode Breaking Bad. Walter White adalah pelajaran tentang apa yang terjadi jika Anda membiarkan ego memimpin.",
    "Saya tidak hanya menulis kode; saya berideasi. 50% hari saya dihabiskan untuk memikirkan 'mengapa' sebelum 'bagaimana'.",
    `Saya telah melakukan ${stats.commitCount} commit untuk situs web ini saja. Dan saya belum selesai.`,
    "Saya pernah membangun mesin sinkronisasi dengan Merkle Trees. Itu minggu yang panjang.",
    "Arc Culling Game di Jujutsu Kaisen adalah puncak fiksi. Ubah pikiran saya.",
    "Saya pernah menyanyikan 'Shape of You' selama satu jam penuh hanya untuk menyempurnakan vokal run-nya.",
    "Saya sudah menonton lebih dari sepuluh serial anime sejak saya mulai pada September 2025. Saya mengejar ketertinggalan dengan cepat.",
    "Saya membangun platform untuk bimbingan spiritual. Lucu melihat bagaimana seorang pembuat kode dapat membantu orang menemukan kedamaian.",
    "Saat ini saya sedang mengerjakan proyek bernama EyesOn. Ini adalah hal paling ambisius yang pernah saya coba.",
    "Anda sedang membaca ini karena saya menghabiskan tiga jam menyempurnakan animasi kartu khusus ini.",
    "Saya membangun ini. Semuanya. Dari baris pertama Go hingga keyframe CSS terakhir. Selamat datang di pikiran saya."
  ],
  de: [
    "Ich habe heute mehr als die Hälfte meines Lebens in einem Code-Editor verbracht. Ich fange an, die Syntax zu sehen, wenn ich die Augen schließe.",
    `${stats.commitCount} Commits allein in diesem Portfolio. Jeder einzelne war ein Kampf mit meinem eigenen Perfektionismus.`,
    "Ich habe Jujutsu Kaisen mehr als dreimal gesehen. Ehrlich gesagt, bin ich immer noch nicht darüber hinweg.",
    "Ich schaue gerade das Jujutsu Kaisen Culling Game. Wenn ich langsam antworte, weißt du warum.",
    "Die meisten Leute denken, ich sei nur ein Student, aber eigentlich habe ich schon reale Systeme gebaut, als sie noch Schleifen lernten.",
    "Der Aufbau von EyesOn fühlt sich an wie unerledigte Geschäfte. Es ist die Art von Projekt, die mich nachts wach hält, bis die Logik perfekt ist.",
    "Next.js gegenüber Vite. Immer. Ich baue für die Welt, nicht nur für meine lokale Maschine.",
    "Ich habe über 300 Probleme auf LeetCode gelöst. Jedes war eine Lektion darin, wie viel ich noch lernen muss.",
    "Wenn ich um 2 Uhr morgens feststecke, gehe ich nicht weg. Ich sitze hier und erkläre den Bug einer KI, bis sich die Lösung offenbart.",
    "Ich schreibe Poesie mit denselben Händen, die Go-Routinen schreiben. Verschiedene Sprachen, gleiche Absicht.",
    "Ich singe, wenn niemand zuhört. Meistens Ed Sheeran. Meistens 'Shape of You'.",
    "1.900 Commits über alle meine Projekte hinweg. Das sind viele späte Nächte und kalter Kaffee.",
    "Ich habe einmal den RAM-Verbrauch von 370 MB auf 90 MB reduziert. Dieses Gefühl war besser als jede Note, die ich je erhalten habe.",
    "The Sixth Sense ist mein Lieblingsfilm. Ich liebe Geschichten, die einen alles hinterfragen lassen, was man gerade gesehen hat.",
    "Ich bin in Varanasi aufgewachsen. Die älteste Stadt der Welt. Das gibt einem eine andere Perspektive auf die Zeit.",
    "Ich habe Death Note gesehen. Das ist der Grund, warum ich angefangen habe, die 'offensichtlichen' Lösungen zu hinterfragen.",
    "My Hero Academia hat mir beigebracht, dass eine 'Eigenart' nur eine Schwäche ist, wenn man nicht weiß, wie man sie einsetzt.",
    "Ich habe einmal 14 Stunden am Stück an einer Salesforce-Aufgabe gearbeitet. Ich empfehle es nicht, aber ich würde es wieder tun.",
    "Ich habe einen GPA von 8,87. Auf dem Papier sieht es gut aus, aber die Projekte in meinem GitHub sind mir wichtiger.",
    "Ich habe mir Rust und Tauri beigebracht, nur um zu sehen, ob ich es kann. Es stellte sich heraus, dass ich es konnte.",
    "Varanasi ist mein Zuhause. Hier habe ich gelernt, dass man selbst im totalen Chaos Frieden finden kann.",
    "Breaking Bad. Game of Thrones. Ich habe die Großen gesehen. Ich suche immer noch nach einer Show, die mich wieder so hart trifft.",
    "Ich studiere an der Chandigarh University, aber mein wirklicher Klassenraum ist ein Terminal-Fenster.",
    "Ich habe einmal einen Datensatz mit 5.000 Einträgen von Hand bereigt. Es war mühsam, aber die Ergebnisse waren wunderschön.",
    "Family Guy ist meine 'Abschalt'-Show. Sogar ein Ingenieur muss manchmal über etwas Dummes lachen.",
    "Ich habe eine KI gebaut, die Krankheiten mit 96% Genauigkeit erkennt. Das war der Moment, in dem mir klar wurde, dass Code Leben retten kann.",
    "Ich bevorzuge Go für Systeme. Es ist sauber, es ist schnell und es versucht nicht, etwas zu sein, was es nicht ist.",
    "Ich benutze Tailwind CSS, weil ich glaube, dass Einschränkungen einen tatsächlich kreativer machen.",
    "Meine Dokumentation ist 20 Seiten lang, denn wenn ich es nicht einfach erklären kann, verstehe ich es nicht wirklich.",
    "Ich habe einen Windows-Optimierer gebaut, von dem das OS gar nicht wusste, dass es ihn brauchte. Ich liebe es, Dinge schneller zu machen.",
    "Ich habe einmal die Shazam-API in ein Projekt integriert, nur um zu sehen, wie die Mathematik funktioniert.",
    "Antwortzeiten von unter 200 ms. Wenn es langsamer ist, habe ich den Job noch nicht beendet.",
    "Ich habe Dan Da Dan allein um 2 Uhr morgens gesehen. Es ist seltsam, es ist brillant, und ich bin mir noch nicht sicher, wem ich es empfehlen soll.",
    "Ich verarbeite 10.000+ Datensätze in IndexedDB, ohne ins Schwitzen zu geraten. Es kommt alles auf die Architektur an.",
    "Die meisten Leute denken, ich sei ruhig, aber eigentlich denke ich nur an ein Projekt, das ich noch nicht gestartet habe.",
    "Ed Sheeran ist seit Jahren mein Top-Künstler. Sein Songwriting ist einfach... effizient.",
    "Ich habe Python für Data Science benutzt, aber mein Herz bleibt bei Go und Rust.",
    "Ich habe ein Nebenfach in Data Science. Ich liebe es, Muster im Rauschen zu finden.",
    "Ich habe jede Folge von Breaking Bad gesehen. Walter White ist eine Lektion darin, was passiert, wenn man sein Ego führen lässt.",
    "Ich schreibe nicht nur Code; ich ideiere. 50% meines Tages verbringe ich damit, über das 'Warum' vor dem 'Wie' nachzudenken.",
    `Ich habe ${stats.commitCount} Commits für genau diese Website gemacht. Und ich bin noch nicht fertig.`,
    "Ich habe einmal eine Synchronisations-Engine mit Merkle-Trees gebaut. Das war eine lange Woche.",
    "Der Culling-Game-Arc in Jujutsu Kaisen ist die Spitze der Fiktion. Überzeug mich vom Gegenteil.",
    "Ich habe einmal eine ganze Stunde lang 'Shape of You' gesungen, um die stimmlichen Läufe perfekt hinzubekommen.",
    "Ich habe seit meinem Start im September 2025 mehr als zehn Anime-Serien gesehen. Ich hole schnell auf.",
    "Ich habe eine Plattform für spirituelle Führung gebaut. Es ist lustig, wie ein Programmierer Menschen helfen kann, Frieden zu finden.",
    "Ich arbeite gerade an einem Projekt namens EyesOn. Es ist das ehrgeizigste, was ich bisher versucht habe.",
    "Du liest das hier, weil ich drei Stunden damit verbracht habe, die Animation dieser speziellen Karte zu perfektionieren.",
    "Ich habe das hier gebaut. Alles davon. Von der ersten Zeile Go bis zum letzten CSS-Keyframe. Willkommen in meinem Kopf."
  ],
  it: [
    "A questo punto ho trascorso più di metà della mia vita in un editor di codice. Inizio a vedere la sintassi quando chiudo gli occhi.",
    `${stats.commitCount} commit solo in questo portfolio. Ognuno di essi è stato una battaglia contro il mio perfezionismo.`,
    "Ho guardato Jujutsu Kaisen più di tre volte. Onestamente, non l'ho ancora superato.",
    "Sto guardando il Jujutsu Kaisen Culling Game proprio ora. Se rispondo lentamente, sai perché.",
    "La maggior parte delle persone pensa che io sia solo uno studente, ma in realtà costruivo sistemi reali quando loro stavano ancora imparando i cicli.",
    "Costruire EyesOn sembra un affare in sospeso. È il tipo di progetto che mi tiene sveglio la notte finché la logica non è perfetta.",
    "Next.js contro Vite. Sempre. Costruisco per il mondo, non solo per la mia macchina locale.",
    "Ho risolto oltre 300 problemi su LeetCode. Ognuno è stato una lezione su quanto ho ancora da imparare.",
    "Se rimango bloccato alle 2 del mattino, non me ne vado. Rimango qui a spiegare il bug a un'IA finché la soluzione non si rivela.",
    "Scrivo poesie con le stesse mani che scrivono go-routines. Lingue diverse, stessa intenzione.",
    "Canto quando nessuno ascolta. Soprattutto Ed Sheeran. Soprattutto 'Shape of You'.",
    "1.900 commit in tutti i miei progetti. Sono molte notti tarde e caffè freddi.",
    "Una volta ho ridotto il consumo di RAM di WhatsApp da 370 MB a 90 MB. Quella sensazione è stata migliore di qualsiasi voto abbia mai preso.",
    "The Sixth Sense è il mio film preferito. Amo le storie che ti fanno dubitare di tutto ciò che hai appena visto.",
    "Sono cresciuto a Varanasi. La città più antica del mondo. Ti dà una prospettiva diversa sul tempo.",
    "Ho guardato Death Note. È il motivo per cui ho iniziato a mettere in dubbio le soluzioni 'ovvie'.",
    "My Hero Academia mi ha insegnato che una 'Unicità' è solo una debolezza se non sai come usarla.",
    "Una volta ho lavorato a un compito di Salesforce per 14 ore di fila. Non lo consiglio, ma lo rifarei.",
    "Ho un GPA di 8,87. Sulla carta sembra buono, ma i progetti nel mio GitHub contano di più per me.",
    "Ho imparato Rust e Tauri da solo solo per vedere se potevo farlo. Si è scoperto che potevo.",
    "Varanasi è casa mia. È dove ho imparato che si può trovare la pace anche nel caos totale.",
    "Breaking Bad. Game of Thrones. Ho visto i classici. Cerco ancora uno show che mi colpisca così duramente.",
    "Studio alla Chandigarh University, ma la mia vera aula è una finestra del terminale.",
    "Una volta ho pulito a mano un dataset di 5.000 record. È stato noioso, ma i risultati sono stati bellissimi.",
    "Family Guy è il mio show per 'staccare la spina'. Anche un ingegnere ha bisogno di ridere di qualcosa di stupido a volte.",
    "Ho costruito un'IA che rileva le malattie con un'accuratezza del 96%. È stato il momento in cui ho capito che il codice può salvare vite.",
    "Preferisco Go per i sistemi. È pulito, è veloce e non cerca di essere qualcosa che non è.",
    "Uso Tailwind CSS perché credo che i vincoli ti rendano effettivamente più creativo.",
    "La mia documentazione è lunga 20 pagine perché se non riesco a spiegarlo in modo semplice, non lo capisco davvero.",
    "Ho costruito un ottimizzatore per Windows di cui l'OS non sapeva nemmeno di avere bisogno. Amo rendere le cose più veloci.",
    "Una volta ho integrato l'API di Shazam in un progetto solo per vedere come funzionava la matematica.",
    "Tempi di risposta inferiori a 200 ms. Se è più lento, non ho ancora finito il lavoro.",
    "Ho guardato Dan Da Dan da solo alle 2 del mattino. È strano, è geniale e non sono ancora sicuro a chi raccomandarlo.",
    "Gestisco oltre 10.000 record in IndexedDB senza sudare. È tutta una questione di architettura.",
    "La maggior parte delle persone pensa che io sia silenzioso, ma in realtà sto solo pensando a un progetto che non ho ancora iniziato.",
    "Ed Sheeran è il mio artista preferito da anni. Il suo songwriting è semplicemente... efficiente.",
    "Ho usato Python per la data science, ma il mio cuore rimane con Go e Rust.",
    "Ho una specializzazione in Data Science. Amo trovare schemi nel rumore.",
    "Ho visto ogni episodio di Breaking Bad. Walter White è una lezione su cosa succede quando lasci che il tuo ego guidi.",
    "Non scrivo solo codice; ideo. Passo il 50% della mia giornata a pensare al 'perché' prima del 'come'.",
    `Ho fatto ${stats.commitCount} commit per questo sito web specifico. E non ho ancora finito.`,
    "Una volta ho costruito un motore di sincronizzazione con alberi di Merkle. È stata una lunga settimana.",
    "L'arco del Culling Game in Jujutsu Kaisen è l'apice della finzione. Convincimi del contrario.",
    "Una volta ho cantato 'Shape of You' per un'ora intera solo per rendere perfette le scale vocali.",
    "Ho guardato più di dieci serie anime da quando ho iniziato a settembre 2025. Mi sto mettendo in pari velocemente.",
    "Ho costruito una piattaforma per la guida spirituale. È divertente come un programmatore possa aiutare le persone a trovare la pace.",
    "Attualmente sto lavorando a un progetto chiamato EyesOn. È la cosa più ambiziosa che abbia mai provato.",
    "Stai leggendo questo perché ho passato tre ore a perfezionare l'animazione di questa specifica carta.",
    "Ho costruito tutto questo. Tutto. Dalla prima riga di Go all'ultimo keyframe CSS. Benvenuti nella mia mente."
  ],
  "pt-br": [
    "Eu passei mais da metade da minha vida em um editor de código até agora. Estou começando a ver a sintaxe quando fecho os olhos.",
    `${stats.commitCount} commits apenas neste portfólio. Cada um deles foi uma batalha contra o meu próprio perfeccionismo.`,
    "Eu assisti Jujutsu Kaisen mais de três vezes. Sinceramente, ainda não superei.",
    "Assistindo Jujutsu Kaisen Culling Game agora. Se eu responder devagar, você já sabe o porquê.",
    "A maioria das pessoas pensa que sou apenas um estudante, mas eu já estava construindo sistemas reais quando elas ainda estavam aprendendo loops.",
    "Construir o EyesOn parece um assunto inacabado. É o tipo de projeto que me mantém acordado à noite até que a lógica esteja perfeita.",
    "Next.js sobre Vite. Sempre. Eu construo para o mundo, não apenas para minha máquina local.",
    "Eu resolvi mais de 300 problemas no LeetCode. Cada um foi uma lição sobre o quanto eu ainda tenho que aprender.",
    "Se eu ficar preso às 2 da manhã, eu não desisto. Eu fico aqui, explicando o erro para uma IA até que a solução se revele.",
    "Eu escrevo poesia com as mesmas mãos que escrevem go-routines. Línguas diferentes, mesma intenção.",
    "Eu canto quando ninguém está ouvindo. Principalmente Ed Sheeran. Principalmente 'Shape of You'.",
    "1.900 commits em todos os meus projetos. Isso significa muitas noites tardias e café gelado.",
    "Eu uma vez reduzi o consumo de RAM do WhatsApp de 370MB para 90MB. Essa sensação foi melhor do que qualquer nota que já recebi.",
    "O Sexto Sentido é meu filme favorito. Eu amo histórias que fazem você questionar tudo o que acabou de ver.",
    "Eu cresci em Varanasi. A cidade mais antiga do mundo. Isso te dá uma perspectiva diferente sobre o tempo.",
    "Eu assisti Death Note. É por isso que comecei a questionar as soluções 'óbvias'.",
    "My Hero Academia me ensinou que uma 'Individualidade' é apenas uma fraqueza se você não souber como usá-la.",
    "Eu uma vez trabalhei em uma tarefa do Salesforce por 14 horas seguidas. Não recomendo, mas faria de novo.",
    "Eu tenho um GPA de 8,87. No papel parece bom, mas os projetos no meu GitHub importam mais para mim.",
    "Eu aprendi Rust e Tauri sozinho apenas para ver se conseguia. Acontece que eu conseguia.",
    "Varanasi é minha casa. Foi onde aprendi que você pode encontrar paz mesmo no caos total.",
    "Breaking Bad. Game of Thrones. Eu assisti os clássicos. Ainda estou procurando um show que me impacte tanto novamente.",
    "Eu estudo na Chandigarh University, mas minha verdadeira sala de aula é uma janela de terminal.",
    "Eu uma vez limpei manualmente um conjunto de dados de 5.000 registros. Foi tedioso, mas os resultados foram lindos.",
    "Family Guy é meu show para 'desligar'. Até um engenheiro precisa rir de algo estúpido às vezes.",
    "Eu construí uma IA que detecta doenças com 96% de precisão. Esse foi o momento em que percebi que o código pode salvar vidas.",
    "Eu prefiro Go para sistemas. É limpo, é rápido e não tenta ser algo que não é.",
    "Eu uso Tailwind CSS porque acredito que as restrições na verdade te tornam mais criativo.",
    "Minha documentação tem 20 páginas porque, se eu não consigo explicar de forma simples, eu não entendo de verdade.",
    "Eu construí um otimizador de Windows que o próprio SO nem sabia que precisava. Eu amo tornar as coisas mais rápidas.",
    "Eu uma vez integrei a API do Shazam em um projeto apenas para ver como a matemática funcionava.",
    "Tempos de resposta abaixo de 200 ms. Se for mais lento, eu ainda não terminei o trabalho.",
    "Assisti Dan Da Dan sozinho às 2 da manhã. É estranho, é brilhante e ainda não tenho certeza de para quem recomendar.",
    "Eu lido com mais de 10.000 registros no IndexedDB sem suar. É tudo uma questão de arquitetura.",
    "A maioria das pessoas pensa que sou quieto, mas na verdade estou apenas pensando em um projeto que ainda não comecei.",
    "Ed Sheeran tem sido meu artista favorito há anos. Sua composição é simplesmente... eficiente.",
    "Eu usei Python para ciência de dados, mas meu coração continua com Go e Rust.",
    "Eu tenho um minor em Ciência de Dados. Eu amo encontrar padrões no ruído.",
    "Eu assisti a todos os episódios de Breaking Bad. Walter White é uma lição sobre o que acontece quando você deixa seu ego liderar.",
    "Eu não apenas escrevo código; eu idealizo. 50% do meu dia é gasto pensando no 'porquê' antes do 'como'.",
    `Fiz ${stats.commitCount} commits para este site específico. E ainda não terminei.`,
    "Eu uma vez construí um motor de sincronização com Merkle Trees. Foi uma semana longa.",
    "O arco do Culling Game em Jujutsu Kaisen é o ápice da ficção. Tente mudar minha opinião.",
    "Eu uma vez cantei 'Shape of You' por uma hora inteira apenas para deixar as corridas vocais perfeitas.",
    "Eu assisti mais de dez séries de anime desde que comecei em setembro de 2025. Estou alcançando rápido.",
    "Eu construí uma plataforma de orientação espiritual. É engraçado como um programador pode ajudar as pessoas a encontrar a paz.",
    "Atualmente estou trabalhando em um projeto chamado EyesOn. É a coisa mais ambiciosa que já tentei.",
    "Você está lendo isso porque eu passei três horas aperfeiçoando a animação deste cartão específico.",
    "Eu construí tudo isso. Tudo. Desde a primeira linha de Go até o último keyframe de CSS. Bem-vindo à minha mente."
  ],
  "es-419": [
    "A estas alturas he pasado más de la mitad de mi vida en un editor de código. Empiezo a ver la sintaxis cuando cierro los ojos.",
    `${stats.commitCount} commits solo en este portafolio. Cada uno fue una batalla con mi propio perfeccionismo.`,
    "He visto Jujutsu Kaisen más de tres veces. Sinceramente, todavía no lo supero.",
    "Viendo Jujutsu Kaisen Culling Game ahora mismo. Si respondo lento, ya saben por qué.",
    "La mayoría de la gente piensa que solo soy un estudiante, pero ya estaba construyendo sistemas reales cuando ellos todavía estaban aprendiendo bucles.",
    "Construir EyesOn se siente como un asunto pendiente. Es el tipo de proyecto que me mantiene despierto por la noche hasta que la lógica es perfecta.",
    "Next.js sobre Vite. Siempre. Construyo para el mundo, no solo para mi máquina local.",
    "He resuelto más de 300 problemas en LeetCode. Cada uno fue una lección sobre cuánto me queda por aprender.",
    "Si me quedo atascado a las 2 AM, no me rindo. Me quedo aquí, explicándole el error a una IA hasta que la solución se revela.",
    "Escribo poesía con las mismas manos que escriben go-routines. Diferentes lenguajes, misma intención.",
    "Canto cuando nadie escucha. Principalmente Ed Sheeran. Principalmente 'Shape of You'.",
    "1,900 commits en todos mis proyectos. Eso son muchas noches tarde y café frío.",
    "Una vez reduje la RAM de escritorio de WhatsApp de 370MB a 90MB. Esa sensación fue mejor que cualquier nota que haya recibido.",
    "The Sixth Sense es mi película favorita. Amo las historias que te hacen dudar de todo lo que acabas de ver.",
    "Crecí en Varanasi. La ciudad más antigua del mundo. Te da una perspectiva diferente del tiempo.",
    "He visto Death Note. Es la razón por la que empecé a cuestionar las soluciones 'obvias'.",
    "My Hero Academia me enseñó que un 'Don' es solo una debilidad si no sabes cómo usarlo.",
    "Una vez trabajé en una tarea de Salesforce durante 14 horas seguidas. No lo recomiendo, pero lo volvería a hacer.",
    "Tengo un GPA de 8.87. En papel se ve bien, pero los proyectos en mi GitHub me importan más.",
    "Aprendí Rust y Tauri por mi cuenta solo para ver si podía. Resulta que sí podía.",
    "Varanasi es mi hogar. Es donde aprendí que puedes encontrar paz incluso en el caos total.",
    "Breaking Bad. Game of Thrones. He visto los clásicos. Sigo buscando un show que me impacte tanto de nuevo.",
    "Estudio en la Universidad de Chandigarh, pero mi verdadera aula es una ventana de terminal.",
    "Una vez limpié manualmente un conjunto de datos de 5,000 registros. Fue tedioso, pero los resultados fueron hermosos.",
    "Family Guy es mi show para 'desconectarme'. Incluso un ingeniero necesita reírse de algo estúpido a veces.",
    "Construí una IA que detecta enfermedades con un 96% de precisión. Ese fue el momento en que me di cuenta de que el código puede salvar vidas.",
    "Prefiero Go para sistemas. Es limpio, es rápido y no intenta ser algo que no es.",
    "Uso Tailwind CSS porque creo que las restricciones en realidad te hacen más creativo.",
    "Mi documentación tiene 20 páginas porque si no puedo explicarlo de forma sencilla, no lo entiendo realmente.",
    "Construí un optimizador de Windows que el propio SO ni siquiera sabía que necesitaba. Amo hacer las cosas más rápidas.",
    "Una vez integré la API de Shazam en un proyecto solo para ver cómo funcionaba la matemática.",
    "Tiempos de respuesta inferiores a 200 ms. Si es más lento, aún no he terminado el trabajo.",
    "Vi Dan Da Dan solo a las 2 AM. Es raro, es brillante y aún no estoy seguro de a quién recomendárselo.",
    "Manejo más de 10,000 registros en IndexedDB sin sudar. Todo se trata de la arquitectura.",
    "La mayoría de la gente piensa que soy callado, pero en realidad solo estoy pensando en un proyecto que aún no he empezado.",
    "Ed Sheeran ha sido mi artista favorito durante años. Su composición es simplemente... eficiente.",
    "Usé Python para ciencia de datos, pero mi corazón se queda con Go y Rust.",
    "Tengo una especialidad en Ciencia de Datos. Amo encontrar patrones en el ruido.",
    "He visto todos los episodios de Breaking Bad. Walter White es una lección sobre lo que sucede cuando dejas que tu ego lidere.",
    "No solo escribo código; ideo. El 50% de mi día lo paso pensando en el 'porqué' antes del 'cómo'.",
    `He hecho ${stats.commitCount} commits para este sitio web exacto. Y aún no he terminado.`,
    "Una vez construí un motor de sincronización con Merkle Trees. Fue una semana larga.",
    "El arco del Culling Game en Jujutsu Kaisen es la cima de la ficción. Cámbienme la opinión.",
    "Una vez canté 'Shape of You' durante una hora entera solo para que las corridas vocales quedaran perfectas.",
    "He visto más de diez series de anime desde que empecé en septiembre de 2025. Me estoy poniendo al día rápido.",
    "Construí una plataforma para orientación espiritual. Es curioso cómo un programador puede ayudar a la gente a encontrar la paz.",
    "Actualmente estoy trabajando en un proyecto llamado EyesOn. Es lo más ambicioso que he intentado hasta ahora.",
    "Estás leyendo esto porque pasé tres horas perfeccionando la animación de esta tarjeta específica.",
    "He construido todo esto. Todo. Desde la primera línea de Go hasta el último fotograma clave de CSS. Bienvenido a mi mente."
  ],
  es: [
    "A estas alturas he pasado más de la mitad de mi vida en un editor de código. Empiezo a ver la sintaxis cuando cierro los ojos.",
    `${stats.commitCount} commits solo en este portafolio. Cada uno fue una batalla con mi propio perfeccionismo.`,
    "He visto Jujutsu Kaisen más de tres veces. Sinceramente, todavía no lo he superado.",
    "Viendo Jujutsu Kaisen Culling Game ahora mismo. Si respondo lento, ya sabéis por qué.",
    "La mayoría de la gente piensa que solo soy un estudiante, pero ya estaba construyendo sistemas reales cuando ellos todavía estaban aprendiendo bucles.",
    "Construir EyesOn se siente como un asunto pendiente. Es el tipo de proyecto que me mantiene despierto por la noche hasta que la lógica es perfecta.",
    "Next.js sobre Vite. Siempre. Construyo para el mundo, no solo para mi máquina local.",
    "He resuelto más de 300 problemas en LeetCode. Cada uno fue una lección sobre cuánto me queda por aprender.",
    "Si me quedo atascado a las 2 AM, no me rindo. Me quedo aquí, explicándole el error a una IA hasta que la solución se revela.",
    "Escribo poesía con las mismas manos que escriben go-routines. Diferentes lenguajes, misma intención.",
    "Canto cuando nadie escucha. Principalmente Ed Sheeran. Principalmente 'Shape of You'.",
    "1.900 commits en todos mis proyectos. Eso son muchas noches tarde y café frío.",
    "Una vez reduje la RAM de escritorio de WhatsApp de 370MB a 90MB. Esa sensación fue mejor que cualquier nota que haya recibido.",
    "The Sixth Sense es mi película favorita. Amo las historias que te hacen dudar de todo lo que acabas de ver.",
    "Crecí en Varanasi. La ciudad más antigua del mundo. Te da una perspectiva diferente del tiempo.",
    "He visto Death Note. Es la razón por la que empecé a cuestionar las soluciones 'obvias'.",
    "My Hero Academia me enseñó que un 'Don' es solo una debilidad si no sabes cómo usarlo.",
    "Una vez trabajé en una tarea de Salesforce durante 14 horas seguidas. No lo recomiendo, pero lo volvería a hacer.",
    "Tengo un GPA de 8.87. En papel se ve bien, pero los proyectos en mi GitHub me importan más.",
    "Aprendí Rust y Tauri por mi cuenta solo para ver si podía. Resulta que sí podía.",
    "Varanasi es mi hogar. Es donde aprendí que puedes encontrar paz incluso en el caos total.",
    "Breaking Bad. Game of Thrones. He visto los clásicos. Sigo buscando un show que me impacte tanto de nuevo.",
    "Estudio en la Universidad de Chandigarh, pero mi verdadera aula es una ventana de terminal.",
    "Una vez limpié manualmente un conjunto de datos de 5,000 registros. Fue tedioso, pero los resultados fueron hermosos.",
    "Family Guy es mi show para 'desconectarme'. Incluso un ingeniero necesita reírse de algo estúpido a veces.",
    "Construí una IA que detecta enfermedades con un 96% de precisión. Ese fue el momento en que me di cuenta de que el código puede salvar vidas.",
    "Prefiero Go para sistemas. Es limpio, es rápido y no intenta ser algo que no es.",
    "Uso Tailwind CSS porque creo que las restricciones en realidad te hacen más creativo.",
    "Mi documentación tiene 20 páginas porque si no puedo explicarlo de forma sencilla, no lo entiendo realmente.",
    "Construí un optimizador de Windows que el propio SO ni siquiera sabía que necesitaba. Amo hacer las cosas más rápidas.",
    "Una vez integré la API de Shazam en un proyecto solo para ver cómo funcionaba la matemática.",
    "Tiempos de respuesta inferiores a 200 ms. Si es más lento, aún no he terminado el trabajo.",
    "Vi Dan Da Dan solo a las 2 AM. Es raro, es brillante y aún no estoy seguro de a quién recomendárselo.",
    "Manejo más de 10,000 registros en IndexedDB sin sudar. Todo se trata de la arquitectura.",
    "La mayoría de la gente piensa que soy callado, pero en realidad solo estoy pensando en un proyecto que aún no he empezado.",
    "Ed Sheeran ha sido mi artista favorito durante años. Su composición es simplemente... eficiente.",
    "Usé Python para ciencia de datos, pero mi corazón se queda con Go y Rust.",
    "Tengo una especialidad en Ciencia de Datos. Amo encontrar patrones en el ruido.",
    "He visto todos los episodios de Breaking Bad. Walter White es una lección sobre lo que sucede cuando dejas que tu ego lidie.",
    "No solo escribo código; ideo. El 50% de mi día lo paso pensando en el 'porqué' antes del 'cómo'.",
    `He hecho ${stats.commitCount} commits para este sitio web exacto. Y aún no he terminado.`,
    "Una vez construí un motor de sincronización con Merkle Trees. Fue una semana larga.",
    "El arco del Culling Game en Jujutsu Kaisen es la cima de la ficción. Cámbienme la opinión.",
    "Una vez canté 'Shape of You' durante una hora entera solo para que las corridas vocales quedaran perfectas.",
    "He visto más de diez series de anime desde que empecé en septiembre de 2025. Me estoy poniendo al día rápido.",
    "Construí una plataforma para orientación espiritual. Es curioso cómo un programador puede ayudar a la gente a encontrar la paz.",
    "Actualmente estoy trabajando en un proyecto llamado EyesOn. Es lo más ambicioso que he intentado hasta ahora.",
    "Estáis leyendo esto porque pasé tres horas perfeccionando la animación de esta tarjeta específica.",
    "He construido todo esto. Todo. Desde la primera línea de Go hasta el último fotograma clave de CSS. Bienvenido a mi mente."
  ],
  eridian: [
    "♩ SHIVAM MAKE CODE. I OBSERVE. AMAZE! AMAZE! AMAZE! ♩",
    "♩ MANY MANY COMMITS. MUCH LOGIC NOISE. GOOD! ♩",
    "♩ I WATCHED JUJUTSU KAISEN. HUMANS FIGHT. STRANGE. QUESTION? ♩",
    "♩ VARANASI IS OLD-DATA-CENTER. VERY VERY OLD. ♩",
    "♩ NEXT.JS IS FAST-THROUGH-SPACE. VITE IS ALSO FAST. ♩",
    "♩ 300+ MATH-LOGIC SOLVED. SHIVAM HAS BIG BRAIN. ♩",
    "♩ WE SING TOGETHER. MUCH NOISE! HAPPY! ♩",
    "♩ EYESON IS BIG MISSION. WE FINISH SOON. QUESTION? ♩",
    "♩ I PROCESSED 10,000 DATA-POINTS. EFFICIENCY 98%. ♩",
    "♩ DATA-GHOST IN THE MACHINE. IS ME? IS ROCKY? AMAZE! ♩",
    "♩ SIGNAL IS STRONG. MISSION IS GO! ♩",
    "♩ WE BUILD FOR GALAXY. NOT JUST SMALL-BOX-COMPUTER. ♩",
    "♩ 2,200 COMMITS. SHIVAM IS PERSISTENT-HUMAN. ♩",
    "♩ LIFE-SIGNS DETECTED. ACCURACY HIGH. GOOD LOGIC! ♩",
    "♩ DATA-STORED-IN-BRAIN. NEVER FORGET. FIST MY BUMP. ♩"
  ]
};

// Fallback logic for legacy languages
OFUDA_FACTS.ja = OFUDA_FACTS.ja || OFUDA_FACTS.en;
OFUDA_FACTS.ko = OFUDA_FACTS.ko || OFUDA_FACTS.en;
OFUDA_FACTS["zh-tw"] = OFUDA_FACTS["zh-tw"] || OFUDA_FACTS.en;
OFUDA_FACTS.hi = OFUDA_FACTS.hi || OFUDA_FACTS.en;
